# Generated by Django 2.0.6 on 2018-07-04 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('D', 'Disponivel'), ('P', 'Na pelada'), ('R', 'Removido')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempos', models.CharField(choices=[('T1', '1 Tempo'), ('T2', '2 Tempos')], max_length=1)),
                ('tempo_duracao', models.TimeField()),
                ('limite_gols', models.CharField(choices=[('1', '1 GOL'), ('2', '2 GOLS'), ('3', '3 GOLS'), ('4', '4 GOLS'), ('5', '5 GOLS')], max_length=1)),
                ('qtd_jogadores', models.CharField(choices=[('5', '5 Jogadores'), ('6', '6 Jogadores'), ('7', '7 Jogadores'), ('8', '8 Jogadores'), ('9', '9 Jogadores'), ('10', '10 Jogadores'), ('11', '11 Jogadores'), ('12', '12 Jogadores')], max_length=1)),
                ('tipo_sorteio', models.CharField(choices=[('O', 'Ordem de chegada'), ('S', 'Sem sorteio'), ('N', 'Nivel Tecnico')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoChecking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('D', 'Disponivel'), ('P', 'Na pelada'), ('R', 'Removido')], max_length=1)),
                ('to_status', models.CharField(choices=[('D', 'Disponivel'), ('P', 'Na pelada'), ('R', 'Removido')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rating', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Gol')),
            ],
        ),
        migrations.CreateModel(
            name='Pelada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('configuracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Configuracao')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peladas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('jogadores', models.ManyToManyField(related_name='times', to='players.Jogador')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='players.Pelada')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='players.Time'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='pelada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='players.Pelada'),
        ),
        migrations.AddField(
            model_name='historicochecking',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='players.Jogador'),
        ),
        migrations.AddField(
            model_name='gol',
            name='jogador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gols_jogador', to='players.Jogador'),
        ),
        migrations.AddField(
            model_name='gol',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gols_time', to='players.Time'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='jogador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='players.Jogador'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='pelada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='players.Pelada'),
        ),
    ]
