# Generated by Django 2.0.6 on 2018-08-20 03:36

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\+\\d{13}|\\(\\d{2}\\)[ ]\\d{5}-\\d{4}$'), 'A phone number must be on this format: (99) 99999-9999', 'invalid')], verbose_name='Phone Number'),
        ),
    ]
